//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bagdad.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bagdad.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your phone is in airplane mode..
        /// </summary>
        public static string AirplaneMode {
            get {
                return ResourceManager.GetString("AirplaneMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a agregar.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elemento de menú.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bagdad.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can&apos;t connect.
        /// </summary>
        public static string CanConnect {
            get {
                return ResourceManager.GetString("CanConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter.
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shootr will never post without your permission..
        /// </summary>
        public static string FacebookAdvice1 {
            get {
                return ResourceManager.GetString("FacebookAdvice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FIND FRIENDS.
        /// </summary>
        public static string FindFriends {
            get {
                return ResourceManager.GetString("FindFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Free.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shootr is free. No ads. No fees..
        /// </summary>
        public static string FreeInfo {
            get {
                return ResourceManager.GetString("FreeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fun.
        /// </summary>
        public static string Fun {
            get {
                return ResourceManager.GetString("Fun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shootr is instant, 24 hours a day fun..
        /// </summary>
        public static string FunInfo {
            get {
                return ResourceManager.GetString("FunInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id or Password are not valid..
        /// </summary>
        public static string GeneralLoginError {
            get {
                return ResourceManager.GetString("GeneralLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Watching.
        /// </summary>
        public static string ImWatching {
            get {
                return ResourceManager.GetString("ImWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Password is in an invalid format..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Username or Email are in an invalid format..
        /// </summary>
        public static string InvalidUserOrEmail {
            get {
                return ResourceManager.GetString("InvalidUserOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ME.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOLLOWERS.
        /// </summary>
        public static string MeFollowers {
            get {
                return ResourceManager.GetString("MeFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOLLOWING.
        /// </summary>
        public static string MeFollowing {
            get {
                return ResourceManager.GetString("MeFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PEOPLE.
        /// </summary>
        public static string MePeople {
            get {
                return ResourceManager.GetString("MePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a POINTS.
        /// </summary>
        public static string MePoints {
            get {
                return ResourceManager.GetString("MePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create New Account.
        /// </summary>
        public static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shootr connects you with friends and family..
        /// </summary>
        public static string NewInfo {
            get {
                return ResourceManager.GetString("NewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s a problem connecting with the internet. Check your connection and try again..
        /// </summary>
        public static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The network connection was lost.
        /// </summary>
        public static string NoInternetConnection {
            get {
                return ResourceManager.GetString("NoInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No one watching.
        /// </summary>
        public static string NoOneWatching {
            get {
                return ResourceManager.GetString("NoOneWatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no results for .
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Shots.
        /// </summary>
        public static string NoShoots {
            get {
                return ResourceManager.GetString("NoShoots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Share with friends about football..
        /// </summary>
        public static string NoShootsSubtitle {
            get {
                return ResourceManager.GetString("NoShootsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDIT PROFILE.
        /// </summary>
        public static string ProfileButtonEdit {
            get {
                return ResourceManager.GetString("ProfileButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOLLOW.
        /// </summary>
        public static string ProfileButtonFollow {
            get {
                return ResourceManager.GetString("ProfileButtonFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FOLLOWING.
        /// </summary>
        public static string ProfileButtonFollowing {
            get {
                return ResourceManager.GetString("ProfileButtonFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register with Email.
        /// </summary>
        public static string RegisterWithEmail {
            get {
                return ResourceManager.GetString("RegisterWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a es-es.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There&apos;s a problem retriving data, please try again later..
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shoot.
        /// </summary>
        public static string Shoot {
            get {
                return ResourceManager.GetString("Shoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shootr.
        /// </summary>
        public static string Shooter {
            get {
                return ResourceManager.GetString("Shooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shootr is a new way to share football..
        /// </summary>
        public static string ShooterInfo {
            get {
                return ResourceManager.GetString("ShooterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Whoops! You already shot that..
        /// </summary>
        public static string ShootRepeated {
            get {
                return ResourceManager.GetString("ShootRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shot not posted.
        /// </summary>
        public static string ShotNotPosted {
            get {
                return ResourceManager.GetString("ShotNotPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shots.
        /// </summary>
        public static string Shots {
            get {
                return ResourceManager.GetString("Shots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sign In with Facebook.
        /// </summary>
        public static string SignWithFacebook {
            get {
                return ResourceManager.GetString("SignWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Shooting.
        /// </summary>
        public static string StartShooting {
            get {
                return ResourceManager.GetString("StartShooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Syncing....
        /// </summary>
        public static string Synchroning {
            get {
                return ResourceManager.GetString("Synchroning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TIMELINE.
        /// </summary>
        public static string TimeLine {
            get {
                return ResourceManager.GetString("TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The request timed out..
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unfollow.
        /// </summary>
        public static string unFollowQuestion {
            get {
                return ResourceManager.GetString("unFollowQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email or Username.
        /// </summary>
        public static string UserOrEmail {
            get {
                return ResourceManager.GetString("UserOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User or Password doesn&apos;t match..
        /// </summary>
        public static string UserOrPasswordDoesntMatch {
            get {
                return ResourceManager.GetString("UserOrPasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a shoot something.
        /// </summary>
        public static string WhatsUp {
            get {
                return ResourceManager.GetString("WhatsUp", resourceCulture);
            }
        }
    }
}
