image: sloydev/android-env:latest

before_script:

features:
    script:
        - ./gradlew checkstyle build
        - gradle test
    stage: test
    only:
        - /^feature\/.*$/

integration:
    script:
        - ./gradlew checkstyle build
        - gradle build -PdisablePreDex
    stage: test
    only:
        - master
        - develop
        - /^bugfix\/.*$/

distribution:
    script: gradle assembleProdRelease -PdisablePreDex publishProdReleaseApkToS3
    stage: deploy
    only:
        - master