before_script:

features:
    script: ./gradlew test
    only:
        - /^feature\/.*$/

integration:
    script: ./gradlew build -PdisablePreDex
    only:
        - develop
        - /^bugfix\/.*$/

distribution:
    script: ./gradlew assembleRelease -PdisablePreDex publishreleaseApkToS3
    stage: deploy
    only:
        - master