before_script:

features:
    script: ./gradlew test
    only:
        - /^feature\/.*$/

integration:
    script: ./gradlew build -PdisablePreDex
    only:
        - develop
        - /^bugfix\/.*$/

sonar:
    script: ./gradlew sonarRunner
    stage: deploy
    only:
        - master
        - sonar
    allow_failure: true