image: sloydev/android-env:latest

before_script:

features:
    script:
        - ./gradlew checkstyle build -Dpre-dex=false -Pcom.android.build.threadPoolSize=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xms512m -Xmx512m" -Dorg.gradle.daemon=false
    stage: test
    only:
        - /^feature\/.*$/

integration:
    script:
        - ./gradlew checkstyle build -Dpre-dex=false -Pcom.android.build.threadPoolSize=1 -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xms512m -Xmx512m" -Dorg.gradle.daemon=false
    stage: test
    only:
        - master
        - develop
        - /^bugfix\/.*$/

distribution:
    script: gradle assembleProdRelease -PdisablePreDex publishProdReleaseApkToS3
    stage: deploy
    only:
        - master