image: sloydev/android-env:23.2

before_script:

features:
    script: gradle test
    stage: test
    only:
        - /^feature\/.*$/

integration:
    script: gradle build -PdisablePreDex
    stage: test
    only:
        - master
        - develop
        - /^bugfix\/.*$/

distribution:
    script: gradle assembleProdRelease -PdisablePreDex publishProdReleaseApkToS3
    stage: deploy
    only:
        - master
