language: android

jdk:
    - oraclejdk8


android:
  components:
    - tools
    - build-tools-25.0.3
    - platform-tools
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-android-support
    - sys-img-armeabi-v7a-android-25
 licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
  - rvm install 2.0.0
  - gem install fastlane -NV

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew checkstyle test coveralls
  - ./fastlane/travis.sh

notifications:
  slack: shootr:kmSZwJMvy1HXouE4UqK5n55s