language: android

jdk:
    - oraclejdk8
android:
  components:
    - tools
    - tools
    - build-tools-25.0.3
    - android-16
    - android-21
    - android-22
    - android-25
    - extra-android-support
    - extra-google-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
before_install:
  - rvm install 2.1.1
  - gem install fastlane -NV

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew checkstyle test coveralls
  - ./fastlane/travis.sh

notifications:
  slack: shootr:kmSZwJMvy1HXouE4UqK5n55s