language: android

jdk:
    - oraclejdk8

android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  # Added cuz Travis doesn't accept license agreements of ConstraintLayout.
  # To fix it, we are copying the licenses that come with the SDK to Travis's directory.
  # Reference: https://github.com/wolkenschieber/License/blob/master/.travis.yml#L35
  - cp ./android-sdk-licenses/* "$ANDROID_HOME/licenses/"
  - rvm install 2.4.1
  - gem install fastlane -NV

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew checkstyle test coveralls
  - ./fastlane/travis.sh

notifications:
  slack: shootr:kmSZwJMvy1HXouE4UqK5n55s