# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.89.0"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  #desc "Runs all the tests"
  #lane :test do
  #  gradle(task: "test")
  #end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean")
    gradle(task: "assembleProdRelease")

    # Single APK upload to Beta by Crashlytics
     crashlytics(
         api_token: "#{ENV["API_TOKEN"]}",
         build_secret: "#{ENV["BUILD_SECRET"]}",
         groups: "dev_team",
         notifications: "true"
     )

  end

  desc "Submit a test apk to S3"
  lane :apk_to_s3 do
    gradle(task: "clean")
    gradle(task: "assembleDev")
    aws_s3(
      access_key: "#{ENV["ACCESS_KEY"]}",
      secret_access_key: "#{ENV["SECRET_ACCESS_KEY"]}",
      bucket: "shootr-nightly-apps",
      app_directory: "android",
      region: 'eu-west-1',
      apk: "#{Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}",
      upload_metadata: false
    )
  end

  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
  #  gradle(task: "assembleRelease")
  #  supply
  #end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is sent or shared. Learn more at https://github.com/fastlane/enhancer
