package com.shootr.android.domain;

public interface ActivityType {

    String CHECKIN = "CHECKIN";
    String START_FOLLOW = "STARTFOLLOW";
    String LISTED_STREAM = "LISTEDSTREAM";
    String PROFILE_UPDATED = "PROFILEUPDATED";
    String JOIN_STREAM = "JOINSTREAM";
    String EXIT_STREAM = "EXITSTREAM";
    String UPDATE_STREAM = "UPDATESTREAM";
    String STARTED_SHOOTING = "STARTEDSHOOTING";

    String[] TYPES_ACTIVITY = { CHECKIN,
      EXIT_STREAM,
      JOIN_STREAM,
      LISTED_STREAM,
      PROFILE_UPDATED,
      START_FOLLOW,
      UPDATE_STREAM,
      STARTED_SHOOTING};

    String[] TYPES_ACTIVITY_SHOWN = { CHECKIN,
      LISTED_STREAM,
      PROFILE_UPDATED,
      START_FOLLOW,
      STARTED_SHOOTING};

    String[] TYPES_SYNC_TRIGGER = { PROFILE_UPDATED,
      JOIN_STREAM,
      EXIT_STREAM,
      UPDATE_STREAM };

}
