package com.shootr.mobile.domain.model;

import java.util.Arrays;
import java.util.List;

public interface ListType {

  String PROMOTED_REPLIES = "PROMOTED_REPLIES";
  String SUBSCRIBERS_REPLIES = "SUBSCRIBERS_REPLIES";
  String OTHER_REPLIES = "OTHER_REPLIES";
  String TIMELINE_ITEMS = "TIMELINE_ITEMS";
  String TIMELINE_H1 = "TIMELINE_H1";
  String TIMELINE_H2 = "TIMELINE_H2";
  String ITEM_DETAIL = "ITEM_DETAIL";
  String PARENTS_DETAIL = "PARENTS_DETAIL";
  String TIMELINE_VIDEOS = "TIMELINE_VIDEOS";
  String TIMELINE_POLLS = "TIMELINE_POLLS";
  String TIMELINE_HIGHLIGHTED_SHOTS = "TIMELINE_HIGHLIGHTED_SHOTS";
  String TIMELINE_PROMOTED_SHOTS = "TIMELINE_PROMOTED_SHOTS";
  String TIMELINE_FOLLOWING_USERS = "TIMELINE_FOLLOWING_USERS";

  List<String> TIMELINE_TYPES =
      Arrays.asList(TIMELINE_ITEMS, TIMELINE_VIDEOS, TIMELINE_POLLS, TIMELINE_HIGHLIGHTED_SHOTS,
          TIMELINE_PROMOTED_SHOTS, TIMELINE_FOLLOWING_USERS);
}
