package com.shootr.mobile.domain.model;

public interface PushSettingType {

  String STARTED_SHOOTING = "STARTEDSHOOTING";
  String NICE_SHOT = "NICESHOT";

  String STARTED_SHOOTING_OFF = "NONE";
  String STARTED_SHOOTING_ALL = "ALL";
  String STARTED_SHOOTING_FAVORITE_STREAMS = "FAVORITE_STREAMS";

  String NICE_SHOT_ALL = "ALL";
  String NICE_SHOT_OFF = "NONE";
  String NICE_SHOT_FOLLOWING = "FOLLOWING";

  String[] TYPES_STARTED_SHOOTING = {
      STARTED_SHOOTING_OFF, STARTED_SHOOTING_FAVORITE_STREAMS, STARTED_SHOOTING_ALL
  };

  String[] TYPES_NICE_SHOT = {
    NICE_SHOT_OFF, NICE_SHOT_FOLLOWING, NICE_SHOT_ALL
  };
}
