package com.shootr.mobile.domain.model;

public interface PushSettingType {

  String STARTED_SHOOTING = "STARTEDSHOOTING";

  String STARTED_SHOOTING_OFF = "NONE";
  String STARTED_SHOOTING_ALL = "ALL";
  String STARTED_SHOOTING_FAVORITE_STREAMS = "FAVORITE_STREAMS";

  String[] TYPES_STARTED_SHOOTING = {
      STARTED_SHOOTING_OFF, STARTED_SHOOTING_FAVORITE_STREAMS, STARTED_SHOOTING_ALL
  };
}
